export const titleMap = {
  home: "Home",
  smartRoute: "Smart Route",
  aiSupport: "AI Support",
  speedometer: "Speed Meter",
  batteryScan: "Battery Scan",
  groupRides: "Group Rides",
  chargingMap: "Charging Map",
  reportStolen: "Report Stolen",
  profile: "Profile",
  subscriptions: "Subscriptions",
  saved: "Saved",
  orders: "Orders & Cards",
  settings: "Settings",
  insurance: "Insurance",
  claimStart: "Start a claim",
  claimStatus: "Claim submitted",
};